/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OwnershipFirm } from "./OwnershipFirm";
import { OwnershipFirmCountArgs } from "./OwnershipFirmCountArgs";
import { OwnershipFirmFindManyArgs } from "./OwnershipFirmFindManyArgs";
import { OwnershipFirmFindUniqueArgs } from "./OwnershipFirmFindUniqueArgs";
import { DeleteOwnershipFirmArgs } from "./DeleteOwnershipFirmArgs";
import { OwnershipFirmService } from "../ownershipFirm.service";
@graphql.Resolver(() => OwnershipFirm)
export class OwnershipFirmResolverBase {
  constructor(protected readonly service: OwnershipFirmService) {}

  async _ownershipFirmsMeta(
    @graphql.Args() args: OwnershipFirmCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OwnershipFirm])
  async ownershipFirms(
    @graphql.Args() args: OwnershipFirmFindManyArgs
  ): Promise<OwnershipFirm[]> {
    return this.service.ownershipFirms(args);
  }

  @graphql.Query(() => OwnershipFirm, { nullable: true })
  async ownershipFirm(
    @graphql.Args() args: OwnershipFirmFindUniqueArgs
  ): Promise<OwnershipFirm | null> {
    const result = await this.service.ownershipFirm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OwnershipFirm)
  async deleteOwnershipFirm(
    @graphql.Args() args: DeleteOwnershipFirmArgs
  ): Promise<OwnershipFirm | null> {
    try {
      return await this.service.deleteOwnershipFirm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
