/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EnergyData } from "./EnergyData";
import { EnergyDataCountArgs } from "./EnergyDataCountArgs";
import { EnergyDataFindManyArgs } from "./EnergyDataFindManyArgs";
import { EnergyDataFindUniqueArgs } from "./EnergyDataFindUniqueArgs";
import { DeleteEnergyDataArgs } from "./DeleteEnergyDataArgs";
import { EnergyDataService } from "../energyData.service";
@graphql.Resolver(() => EnergyData)
export class EnergyDataResolverBase {
  constructor(protected readonly service: EnergyDataService) {}

  async _energyDataItemsMeta(
    @graphql.Args() args: EnergyDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EnergyData])
  async energyDataItems(
    @graphql.Args() args: EnergyDataFindManyArgs
  ): Promise<EnergyData[]> {
    return this.service.energyDataItems(args);
  }

  @graphql.Query(() => EnergyData, { nullable: true })
  async energyData(
    @graphql.Args() args: EnergyDataFindUniqueArgs
  ): Promise<EnergyData | null> {
    const result = await this.service.energyData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EnergyData)
  async deleteEnergyData(
    @graphql.Args() args: DeleteEnergyDataArgs
  ): Promise<EnergyData | null> {
    try {
      return await this.service.deleteEnergyData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
